
version: '2'

services:
  flutend:
    container_name: fluentd
    build: ./fluentd
    volumes: 
      - ./fluentd:/fluentd/etc
    links:
      - "elasticsearch"
    ports: 
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
  
  kibana:
    container_name: kibana
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"